import Foundation
import Testing
@testable import Verdant

/// A bound on the `verifiedBasis` lines, because they are prompt text and they grew a lot in one day.
///
/// The basis is not a log line. It is concatenated into the claim every skeptic and every replication
/// analyst reads (`survives` builds "summary + Verified basis: …"), so every clause added to it is
/// paid once per panelist per finding, out of a 4,096-token window.
///
/// Five clauses were added across these types on 2026-08-02 — a provenance caveat on three kinds, the
/// per-third coefficients, the rank-vs-linear agreement, the mean-shift percentage, and the record's
/// own value. Each was individually cheap and well-motivated, and nothing measured the total. That is
/// exactly how a budget goes: not in one bad decision but in five good ones.
///
/// Measured 2026-08-03, with every optional caveat firing: correlation 473 characters, volatility
/// 401, regime 763. Those first read 337 / 384 / 616 a day earlier, which is the point of printing
/// them — two of the three grew again while nobody was watching the total.
///
/// Treat these three as a snapshot that is probably already wrong. The correlation figure read 461
/// for a few hours, until rewording one parenthetical in `verifiedBasis` — a fix to something else
/// entirely — added twelve characters. Volatility and regime then moved again when the provenance
/// note stopped being transcribed into this file and started being GENERATED by the code that
/// writes it: the hand-copy had understated the real note by eighteen characters, so the worst case
/// was eighteen characters optimistic in two of the three kinds. The number that is ENFORCED is the
/// bound; these are here to show the direction of travel, and the run prints the current values.
///
/// Regime is now within 137 characters of the bound, so it is out of room: the next clause added to
/// it has to displace one, or the bound has to move on a stated argument rather than to make a build
/// pass. What it spent that budget on was worth it — the windows clause is what lets the replication
/// panel re-compute the comparison the finding actually made (`ClaimWindowTests`) — and it is still
/// spent.
struct BasisLengthTests {
    /// ~225 tokens at four characters each — comfortably inside the skeptic's window (that session
    /// carries no tools, so its prefix is instructions alone) while being tight enough that doubling
    /// any of these lines trips it.
    static let maxBasisCharacters = 900

    /// GENERATED, not transcribed. This was a hand-written copy of the note and had already drifted
    /// from it — the real one reads "N days ago, inside {window}" and the copy still said "0 days
    /// from this step, and has held 59 days since", a format the app stopped producing. A worst-case
    /// budget measured against invented text is measuring the wrong worst case, which is the same
    /// way `DirectorStateSizeTests` came to be blind: its saturation fixture kept a constant the app
    /// had replaced.
    ///
    /// Deliberately long inputs — two multi-word device names and a wordy window phrase — because
    /// this fixture exists to be the biggest note a real user could produce, not a typical one.
    private var swapNote: String {
        ProvenanceScan.noteForClaim(
            metric: .restingHeartRate,
            window: "the 59 days this level has held",
            since: Date(timeIntervalSince1970: 1_700_000_000),
            now: Date(timeIntervalSince1970: 1_700_000_000 + 59 * 86400),
            changes: [
                SourceChange(
                    metric: .restingHeartRate,
                    day: Date(timeIntervalSince1970: 1_700_000_000),
                    before: ["Apple Watch Series 8"],
                    after: ["Apple Watch Series 11", "iPhone 17 Pro"],
                    daysBefore: 400,
                    daysAfter: 59
                )
            ]
        ) ?? ""
    }

    /// Every caveat firing at once. A worst case assembled by hand, because the real one appears only
    /// on a user whose watch changed during a weak, drifting, gappy step — which is precisely the
    /// finding that most needs its evidence stated in full.
    /// Prints the worst case per kind, so the remaining room is visible before the next clause is
    /// added rather than after it fails.
    @Test func `report the basis budget`() {
        let shift = RegimeShift(
            metric: .restingHeartRate, changeDay: Date(), preMean: 60, postMean: 56, score: 4.8,
            postDays: 58, medianStepSD: 0.3, maxSegmentTrendR: 0.7, maxPostGapDays: 30,
            suspectedDeviceSwap: true, coJumpingVitals: 4, sourceChangeNote: swapNote
        )
        let volatility = VolatilityShift(
            metric: .restingHeartRate, recentSD: 4, baselineSD: 2, recentMean: 72,
            baselineMean: 60, cvRatio: 2, seZ: 3, n: 30, sourceChangeNote: swapNote
        )
        let correlation = MetricCorrelation(
            metricA: .stepCount, metricB: .restingHeartRate, lag: 2, r: 0.44, partialR: 0.40,
            spearman: 0.20, n: 90, nEff: 60, pValue: 0.31, significant: false,
            activityControlled: true, consistentAcrossThirds: false, thirdsR: [0.78, 0.51, 0.22],
            mechanicallyRedundant: true
        )
        let worst = [
            ("regime", shift.verifiedBasis.count),
            ("volatility", volatility.verifiedBasis.count),
            ("correlation", correlation.verifiedBasis.count)
        ]
        let report = worst
            .map { "\($0.0) \($0.1)" }
            .joined(separator: "  ")
        print("BASIS BUDGET (bound \(Self.maxBasisCharacters), worst case per kind)  \(report)")
    }

    @Test func `the regime basis stays inside its budget with every caveat firing`() {
        let shift = RegimeShift(
            metric: .restingHeartRate, changeDay: Date(), preMean: 60, postMean: 56, score: 4.8,
            postDays: 58, medianStepSD: 0.3, maxSegmentTrendR: 0.7, maxPostGapDays: 30,
            suspectedDeviceSwap: true, coJumpingVitals: 4, sourceChangeNote: swapNote
        )
        let basis = shift.verifiedBasis
        // Non-vacuity: the worst case must actually BE the worst case.
        #expect(basis.contains("RECORDS"), "the provenance caveat did not fire")
        #expect(basis.contains("watch-measured vitals"), "the co-jump caveat did not fire")
        #expect(basis.contains("medians echo"), "the weak-median caveat did not fire")
        #expect(basis.contains("trends internally"), "the drift caveat did not fire")
        #expect(basis.contains("unobserved stretch"), "the gap caveat did not fire")
        #expect(
            basis.count <= Self.maxBasisCharacters,
            Comment(rawValue: "regime basis is \(basis.count) characters")
        )
    }

    @Test func `the volatility basis stays inside its budget`() {
        let shift = VolatilityShift(
            metric: .restingHeartRate, recentSD: 4, baselineSD: 2, recentMean: 72,
            baselineMean: 60, cvRatio: 2, seZ: 3, n: 30, sourceChangeNote: swapNote
        )
        #expect(shift.verifiedBasis.contains("RECORDS"))
        #expect(
            shift.verifiedBasis.count <= Self.maxBasisCharacters,
            Comment(rawValue: "volatility basis is \(shift.verifiedBasis.count) characters")
        )
    }

    @Test func `the correlation basis stays inside its budget`() {
        let corr = MetricCorrelation(
            metricA: .stepCount, metricB: .restingHeartRate, lag: 2, r: 0.44, partialR: 0.40,
            spearman: 0.20, n: 90, nEff: 60, pValue: 0.31, significant: false,
            activityControlled: true, consistentAcrossThirds: false, thirdsR: [0.78, 0.51, 0.22],
            mechanicallyRedundant: true
        )
        let basis = corr.verifiedBasis
        #expect(basis.contains("thirds"), "the thirds clause did not fire")
        #expect(basis.contains("rank-vs-linear"), "the shape clause did not fire")
        #expect(basis.contains("mechanically coupled"), "the redundancy caution did not fire")
        #expect(
            basis.count <= Self.maxBasisCharacters,
            Comment(rawValue: "correlation basis is \(basis.count) characters")
        )
    }

    @Test func `the seasonal and milestone bases stay inside their budget`() {
        let swing = SeasonalSwing(
            metric: .restingHeartRate, swingInUnits: 3.5, peakMonth: 1, peakEffect: 1.2,
            oppositeMonth: 7, oppositeEffect: -1.1, monthsCompared: 12, yearsObserved: 3,
            yearsAgreeing: 3
        )
        #expect(swing.verifiedBasis.count <= Self.maxBasisCharacters)

        let milestone = Milestone(
            metric: .stepCount, recentMean: 12400, isHigh: true, spanDays: 300,
            relativeMargin: 0.08, sourceChangeNote: swapNote
        )
        #expect(milestone.verifiedBasis.contains("RECORDS"))
        #expect(
            milestone.verifiedBasis.count <= Self.maxBasisCharacters,
            Comment(rawValue: "milestone basis is \(milestone.verifiedBasis.count) characters")
        )
    }
}
